version: 2.1

orbs:
  android: circleci/android@2.1.2
  gcp-cli: circleci/gcp-cli@2.4.1
  aws-s3: circleci/aws-s3@3.1

jobs:
  deploy-dev:
    docker:
      - image: "cimg/python:3.10"
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/project
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: ~/project/app/build/outputs/apk/dev/debug/
          to: "s3://deploy-app-vendedor/dev"
  deploy-qa:
    docker:
      - image: "cimg/python:3.10"
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/project
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: ~/project/app/build/outputs/apk/qa/debug/
          to: "s3://deploy-app-vendedor/qa"
  deploy-prd:
    docker:
      - image: "cimg/python:3.10"
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/project
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: ~/project/app/build/outputs/apk/prd/release/
          to: "s3://deploy-app-vendedor/prd"

  dev-build:
    executor:
      name: android/android-docker
      tag: 2022.08.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Assemble dev build
          command: |
            ./gradlew assembleDevDebug
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  qa-build:
    executor:
      name: android/android-docker
      tag: 2022.08.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Assemble qa build
          command: |
            ./gradlew assembleQaDebug
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  prd-build:
    executor:
      name: android/android-docker
      tag: 2022.08.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Assemble prd build
          command: |
            ./gradlew assemblePrdRelease
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  test-and-build:
    jobs:
      - dev-build:
          filters:
            branches:
              only: dev # Commits to main branch
      - deploy-dev:
          filters:
            branches:
              only: dev # Commits to main branch
          requires:
            - dev-build

      - qa-build:
          filters:
            branches:
              only: qas # Commits to main branch
      - deploy-qa:
          filters:
            branches:
              only: qas # Commits to main branch
          requires:
            - qa-build

      - prd-build:
          filters:
            branches:
              only: main # Commits to main branch
      - deploy-prd:
          filters:
            branches:
              only: main # Commits to main branch
          requires:
            - prd-build
